// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © bilardi
//@version=4

//strategy("My Simple Strategy Script - sample 1") // a chart space dedicated
strategy("My Simple Strategy Script - sample 1", "", true) // in the main chart

legs = input(20)
//ma = sma(close, legs)
ma = ema(close, legs)
plot(ma, "Ma", color.orange, 2)
dev = 2 * stdev(close, legs)
upper = ma + dev
lower = ma - dev
p1 = plot(upper, title="BB upper", color=color.green, linewidth=1, style=plot.style_circles)
p2 = plot(lower, title="BB lower", color=color.green, linewidth=1, style=plot.style_circles)
fill(p1, p2)

// Taking the difference between the prices and the MA timeseries
price_ma_diff = close - ma

// Taking the sign of the difference to determine whether the price or the EMA is greater
position = price_ma_diff - price_ma_diff[1]
buyEntry = position >= 2 ? price_ma_diff : na
sellEntry = position <= -2 ? price_ma_diff : na

if (buyEntry)
//    strategy.entry("MaLE", strategy.long, stop=ma, oca_name="Ma", oca_type=strategy.oca.cancel, comment="MaLE")
    strategy.entry("MaLE", strategy.long, oca_name="Ma", oca_type=strategy.oca.cancel, comment="MaLE")
else
    strategy.cancel(id="MaLE")

if (sellEntry)
//    strategy.entry("MaSE", strategy.short, stop=ma, oca_name="Ma", oca_type=strategy.oca.cancel, comment="MaSE")
    strategy.entry("MaSE", strategy.short, oca_name="Ma", oca_type=strategy.oca.cancel, comment="MaSE")
else
    strategy.cancel(id="MaSE")

plot(strategy.equity, title="Equity", color=color.red, linewidth=2, style=plot.style_areabr)